### ISSUE TITLE
github page not showing up

### ISSUE THREAD

**Issue by arjun-Moksh** [Conestoga-AAIML-2023-Spring/CSCN8010-lab-submissions#48]

**Comment by arjun-Moksh** [comment]
need help in creating github pages I tried but it's not showing up

**Comment by RanFeldesh** [comment]
Hi @arjun-Moksh ,

Thanks for creating the issue

I believe that this was because the HTML was not in the `docs` folder, but in the `students_submissions` folder. It is 100% fine to have subfolders within the `docs` root folder - and these will be part of the URL. But the `docs` has to be the root, since this is the folder Github maps into the web-site, as we defined in the repository settings. 

Can you confirm that that was the reason, and if so close the issue?
